### ISSUE TITLE
write on the readme how to load the plugin compiled from source

### ISSUE THREAD

**Issue by gogo2464** [radareorg/r2retdec#27]
The instruction to load the plugin compiled from source is missing. Then I suggest to write what I did.

I built from source. Then, I have an `core_retdec.so` file.

Then I did `r2pm -h` and then see `R2PM_PLUGDIR=/home/MYNAME/.local/share/radare2/plugins` so I did cp `core_retdec.so /home/MYNAME/.local/share/radare2/plugins` and then the plugin works perfectly.

I think we can write it on the readme.

Just tell me if you want it, then I can add it.

**Comment by xkubov** [comment]
Hi, thanks for the suggestion, but if you use `-DCMAKE_INSTALL_PREFIX=~/.local` as stated in README.md the plugin would automatically install into `$HOME/.local/share/radare2/plugins`. I agree that the instructions are not clear on this one. I will try to state this in the `README.md` more clearly.

**Comment by apkunpacker** [comment]
hi . please fix installation on termux , or provide core_retdec.so prebuilt binary for arm/arm64 . thanks
