### ISSUE TITLE
Update on radare2 api

### ISSUE THREAD

**Issue by autquis** [radareorg/r2retdec#35]
Hi! Check this [commit](https://github.com/radareorg/radare2/commit/fdbd440bb7e4f5a33de9af3ee7ea50f1ec63cd79#diff-ef03ef9fc66ec110b53dd7f189a258560e4c09b6c5246fea4053ec5e2a6f7e3e). So, if you try to build `retdec-r2plugin`, you will see this error:
```
/home/xxxxxxx/.local/share/radare2/r2pm/git/retdec-r2plugin/include/r2plugin/r2cgen.h:14:10: fatal error: r_util/r_annotated_code.h: No such file or directory
   14 | #include <r_util/r_annotated_code.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
This happens when `make` tries to build target `core_retdec`.

This #34 will fix this. @xkubov

**Comment by autquis** [comment]
#34

**Comment by gogo2464** [comment]
This should be the priority. Currently retdec-r2plugin can not just be compiled.

**Comment by gogo2464** [comment]
Fell free to assign me please.

**Comment by s3rvac** [comment]
Hello. We are aware of this issue, but we need to first resolve how to deal with the split of radare2 and Rizin (e.g. whether we should support both or just one of them). We are currently having discussions with maintainers of both projects. I am sorry for the inconvenience. Hopefully, everything will be resolved soon.

**Comment by gogo2464** [comment]
@s3rvac will the next commits on your branch solve this issue or should I make a PR on this issue to solve it?

**Comment by s3rvac** [comment]
There is already a PR for that: #34. Like I said, we are aware of this issue, but we want to finish our discussions before we continue.

**Comment by gogo2464** [comment]
Ok then do not assign me.
